[package]
name = "sn-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sn-core = { path = "../core" }
sn-payments = { path = "../payments" }
tokio.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
reqwest.workspace = true

[dev-dependencies]
axum.workspace = true
