'use strict';
const CABINET_FIELDS = [
 ['brand','Название сервиса'],['logo','Логотип · HTTPS-адрес','url'],['logo_dark','Логотип для тёмной темы · HTTPS','url'],['favicon','Favicon · HTTPS-адрес','url'],['accent','Основной цвет','#'],['accent_end','Второй цвет','#'],
 ['headline','Заголовок сайта'],['description','Описание сервиса','textarea'],['tariffs_heading','Заголовок раздела тарифов'],['faq_heading','Заголовок FAQ'],
 ['seo_title','SEO · заголовок страницы'],['seo_description','SEO · описание','textarea'],['og_image','Изображение для превью ссылки · HTTPS','url'],
 ['bot','Username бота для привязки · без @'],['support_url','Ссылка поддержки · HTTPS','url'],['support_label','Подпись ссылки поддержки'],['support_text','Текст раздела поддержки','textarea'],['docs_text','Вступление к документам','textarea']
];
const CABINET_LOCALIZED_FIELDS = CABINET_FIELDS.filter(([k])=>['headline','description','tariffs_heading','faq_heading','seo_title','seo_description','support_label','support_text','docs_text'].includes(k));
registerPage({id:'cabinet',title:'Кабинет и Mini App',group:'Система',icon:'browser',
 render(){return `<div class="page-head"><div><h1>Кабинет и Mini App</h1><p class="desc">Общий клиентский сайт: витрина, вход по коду и приложение Telegram.</p></div><button class="btn" id="cabinetReload">${I('refresh',14)} Обновить статус</button></div><div id="cabinetAdmin" aria-live="polite">Загружаем настройки…</div>`;},
 async bind(root){let data,conf;const owner=DB.admin?.role==='owner',box=root.querySelector('#cabinetAdmin');
 const load=async()=>{try{data=await API.call('/api/cabinet-service');conf=data.config;draw();}catch(e){box.innerHTML=`<p role="alert">${esc(e.message)}</p>`;}};
 function draw(){
 const installations=data.installations.filter(i=>!i.revoked_at), connected=installations.some(i=>i.last_seen_at&&Date.now()-Date.parse(i.last_seen_at)<120000), installed=installations.some(i=>i.last_seen_at);
 const setup=!connected?`<section class="card cabinet-setup" aria-labelledby="cabinetSetupTitle"><div><span class="badge warn">${installed?'Нужна проверка':'Требуется установка'}</span><h2 id="cabinetSetupTitle">${installed?'Кабинет не отвечает':'Кабинет ещё не установлен'}</h2><p>${installed?'Сервер перестал отвечать. Откройте раздел установки и проверьте подключение. Повторно устанавливать работающий сервис не нужно.':'Чтобы заработали сайт, кабинет клиента и Mini App, откройте раздел «Серверы и установка», добавьте сервер и выполните установочную команду по SSH.'}</p><div class="actions"><button class="btn primary" type="button" id="cabinetSetupStart">${I(installed?'server':'download',16)} ${installed?'Проверить подключение':'Установить кабинет'}</button><a class="btn" href="/cabinet-installation.html" target="_blank" rel="noopener">Инструкция по установке</a></div></div></section>`:'';
 box.innerHTML=`${setup}<div class="cabinet-admin-intro"><div><h2>Сайт обслуживает Mini App</h2><p>Без установленного кабинета приложение Telegram недоступно. Выберите сервер ниже: его адрес будет использоваться в кнопке бота и в BotFather.</p></div><a class="btn" href="#/bot">Настройки кнопок бота</a></div><div class="tabs cabinet-admin-tabs" role="tablist"><button class="on" role="tab" aria-selected="true" data-pane="brand">Брендинг и содержимое</button><button role="tab" aria-selected="false" data-pane="install">Серверы и установка</button></div>
 <section data-content="brand"><form id="cabinetForm"><div class="card cabinet-config"><div class="cabinet-config-flags">${[['enabled','Опубликовать кабинет и разрешить Mini App'],['registration_enabled','Регистрация на сайте'],['shop_enabled','Покупка и продление'],['devices_enabled','Управление устройствами'],['referral_enabled','Приглашения'],['tickets_enabled','Обращения в поддержку'],['indexable','Разрешить индексацию сайта']].map(([k,t])=>`<label class="bot-toggle"><span>${t}</span><input type="checkbox" data-cab="${k}" ${conf[k]?'checked':''}></label>`).join('')}</div><p class="hint">Стартовые тексты RU/EN и оформление уже подготовлены — их можно изменить. Чтобы запустить кабинет, включите публикацию и сохраните настройки. Цены и лимиты берутся из <a href="#/tariffs">тарифов</a>.</p><div class="cabinet-fields">${CABINET_FIELDS.map(([k,t,type])=>`<div class="field ${type==='textarea'?'cabinet-wide':''}"><label for="cab-${k}">${t}</label>${type==='textarea'?`<textarea id="cab-${k}" class="inp" data-cab="${k}" rows="3">${esc(conf[k]||'')}</textarea>`:`<input id="cab-${k}" class="inp" data-cab="${k}" value="${esc(conf[k]||'')}" ${type==='url'?'type="url"':type==='#'?'pattern="#[0-9a-fA-F]{6}" maxlength="7"':'type="text"'}>`}</div>`).join('')}</div></div>
 ${[['steps','Шаги подключения','title','Заголовок','text','Описание'],['faq','Вопросы и ответы','question','Вопрос','answer','Ответ'],['docs_links','Документы','title','Название','url','HTTPS-ссылка']].map(([k,t,a,al,b,bl])=>`<section class="card cabinet-editor"><div class="section-h"><h2>${t}</h2><button class="btn sm" type="button" data-add="${k}">${I('plus',14)} Добавить</button></div><div data-rows="${k}">${(conf[k]||[]).map(r=>row(k,r,a,al,b,bl)).join('')}</div></section>`).join('')}<section class="card cabinet-editor"><h2>Содержимое на английском · EN</h2><p class="hint">Русские тексты задаются выше. Заполните английские заголовки, описание и SEO, чтобы опубликовать английскую витрину. Логотипы, цвета, тарифы и аккаунты общие для двух языков.</p><div class="cabinet-fields">${CABINET_LOCALIZED_FIELDS.map(([k,t,type])=>`<div class="field ${type==='textarea'?'cabinet-wide':''}"><label for="cab-en-${k}">${t} · EN</label>${type==='textarea'?`<textarea id="cab-en-${k}" class="inp" data-cab-en="${k}" rows="3">${esc(conf.locales?.en?.[k]||'')}</textarea>`:`<input id="cab-en-${k}" class="inp" data-cab-en="${k}" value="${esc(conf.locales?.en?.[k]||'')}">`}</div>`).join('')}</div></section>${[['steps','Шаги подключения','title','Заголовок','text','Описание'],['faq','Вопросы и ответы','question','Вопрос','answer','Ответ'],['docs_links','Документы','title','Название','url','HTTPS-ссылка']].map(([k,t,a,al,b,bl])=>`<section class="card cabinet-editor"><div class="section-h"><h2>${t} · EN</h2><button class="btn sm" type="button" data-add="en.${k}">${I('plus',14)} Добавить</button></div><div data-rows="en.${k}">${(conf.locales?.en?.[k]||[]).map(r=>row('en.'+k,r,a,al,b,bl)).join('')}</div></section>`).join('')}<div class="cabinet-savebar"><span id="cabinetSaveState" role="status">${data.defaults_applied?'Стартовые тексты добавлены — сохраните настройки':'Настройки сохранены'}</span><button class="btn primary" id="cabinetSave" ${!owner?'disabled':''}>Сохранить настройки</button></div></form></section>
 <section data-content="install" hidden><section class="card cabinet-setup" id="cabinetPublishNotice" ${conf.enabled?'hidden':''}><div><h2>Сначала опубликуйте кабинет</h2><p>Заполните обязательные поля в разделе «Брендинг и содержимое», включите публикацию и сохраните настройки. После этого выполните команду установки на выбранном сервере.</p><button class="btn primary" type="button" id="cabinetPublishStart">${I('edit',16)} Настроить публикацию</button></div></section><div class="card"><div class="section-h"><h2>Размещение кабинета</h2><button class="btn primary sm" id="cabinetNew" ${!owner?'disabled':''}>${I('plus',14)} Добавить сервер</button></div><p class="sub-note">Можно установить рядом с панелью или на отдельный сервер. Нужен отдельный HTTPS-домен с DNS-записью на IP сервера. Сервис не получает доступа к базе данных или админке.</p><div class="field"><label for="miniappInstallation">Кабинет для Mini App</label><select class="inp" id="miniappInstallation" ${!owner?'disabled':''}><option value="">Не выбран · Mini App недоступно</option>${data.installations.filter(i=>!i.revoked_at).map(i=>`<option value="${i.id}" ${conf.miniapp_installation_id===i.id?'selected':''}>${esc(i.name)} · ${esc(i.public_url)}</option>`).join('')}</select><p class="hint">Выбор сохраняется сразу. Кнопка в боте появляется после успешного запуска кабинета и включения Mini App в настройках бота.</p></div><div class="notice">${data.miniapp_url?`Адрес для BotFather: <a href="${esc(data.miniapp_url)}" target="_blank" rel="noopener">${esc(data.miniapp_url)}</a>`:'Mini App сейчас недоступно: проверьте публикацию сайта, выбранный сервер и переключатель в настройках бота.'}</div></div><div class="cabinet-installations">${data.installations.map(i=>`<article class="card"><div class="section-h"><h2>${esc(i.name)}</h2><span class="badge">${i.revoked_at?'Ключ отозван':i.last_seen_at&&Date.now()-Date.parse(i.last_seen_at)<120000?'На связи':i.last_seen_at?'Нет связи':'Не установлен'}</span></div><a href="${esc(i.public_url)}" target="_blank" rel="noopener">${esc(i.public_url)}</a><p class="sub-note">${esc(i.server_ip)} · ${i.placement==='same'?'На сервере панели':'Отдельный сервер'}</p><p class="hint">${i.last_seen_at?'Последний ответ: '+esc(new Date(i.last_seen_at).toLocaleString('ru')):'Запросов от сервера ещё не было'}</p><div class="actions"><button class="btn" data-install="${i.id}" ${!owner?'disabled':''}>${i.token_prefix?'Обновить ключ и команду':'Получить команду установки'}</button>${i.token_prefix&&!i.revoked_at?`<button class="btn danger" data-revoke="${i.id}" ${!owner?'disabled':''}>Отключить сервер</button>`:''}</div></article>`).join('')}</div></section>`;
 box.querySelectorAll('[data-pane]').forEach(b=>b.onclick=()=>{box.querySelectorAll('[data-pane]').forEach(x=>{x.classList.toggle('on',x===b);x.setAttribute('aria-selected',x===b);});box.querySelectorAll('[data-content]').forEach(x=>x.hidden=x.dataset.content!==b.dataset.pane);});
 const publish=()=>{box.querySelector('[data-pane="brand"]').click();box.querySelector('[data-cab="enabled"]').focus();};box.querySelector('#cabinetPublishStart').onclick=publish;
 const start=box.querySelector('#cabinetSetupStart');if(start)start.onclick=()=>{const tab=box.querySelector('[data-pane="install"]');tab.click();tab.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});(installations.length?tab:box.querySelector('#cabinetNew')).focus();};
 box.querySelectorAll('[data-remove-row]').forEach(b=>b.onclick=()=>{b.closest('.cabinet-row').remove();dirty();});
 box.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const k=b.dataset.add,kind=k.replace(/^en\./,''),args=kind==='steps'?['title','Заголовок','text','Описание']:kind==='faq'?['question','Вопрос','answer','Ответ']:['title','Название','url','HTTPS-ссылка'];box.querySelector(`[data-rows="${k}"]`).insertAdjacentHTML('beforeend',row(k,{},...args));const r=box.querySelector(`[data-rows="${k}"]`).lastElementChild;r.querySelector('[data-remove-row]').onclick=()=>{r.remove();dirty();};r.querySelector('input').focus();dirty();});
 const dirty=()=>box.querySelector('#cabinetSaveState').textContent='Есть несохранённые изменения';box.querySelector('#cabinetForm').oninput=dirty;
 box.querySelector('#cabinetForm').onsubmit=async e=>{e.preventDefault();if(!owner)return;const b=box.querySelector('#cabinetSave');b.disabled=true;try{const next={...conf};box.querySelectorAll('[data-cab]').forEach(x=>next[x.dataset.cab]=x.type==='checkbox'?x.checked:x.value.trim());for(const k of ['steps','faq','docs_links'])next[k]=[...box.querySelectorAll(`[data-rows="${k}"] .cabinet-row`)].map(r=>Object.fromEntries([...r.querySelectorAll('[data-part]')].map(x=>[x.dataset.part,x.value.trim()])));next.locales={en:{}};box.querySelectorAll('[data-cab-en]').forEach(x=>next.locales.en[x.dataset.cabEn]=x.value.trim());for(const k of ['steps','faq','docs_links'])next.locales.en[k]=[...box.querySelectorAll(`[data-rows="en.${k}"] .cabinet-row`)].map(r=>Object.fromEntries([...r.querySelectorAll('[data-part]')].map(x=>[x.dataset.part,x.value.trim()])));await API.call('/api/cabinet-service',{method:'PATCH',body:next});conf=next;box.querySelector('#cabinetPublishNotice').hidden=!!conf.enabled;box.querySelector('#cabinetSaveState').textContent='Настройки сохранены';toast('Кабинет и Mini App обновлены');}catch(err){box.querySelector('#cabinetSaveState').textContent=err.message;}finally{b.disabled=false;}};
 box.querySelector('#miniappInstallation').onchange=async e=>{e.target.disabled=true;try{await API.call('/api/cabinet-service',{method:'PATCH',body:{...conf,miniapp_installation_id:e.target.value}});await load();box.querySelector('[data-pane="install"]').click();}catch(err){toast(err.message);e.target.value=conf.miniapp_installation_id||'';e.target.disabled=false;}};
 box.querySelector('#cabinetNew').onclick=()=>openModal({title:'Новый сервер кабинета',icon:'browser',body:`<form id="cabinetNewForm"><div class="field"><label for="installName">Название</label><input class="inp" id="installName" required maxlength="100"></div><div class="field"><label for="installURL">HTTPS-домен</label><input class="inp" id="installURL" type="url" placeholder="https://clients.example.com" required></div><div class="field"><label for="installIP">IP сервера</label><input class="inp" id="installIP" required></div><div class="field"><label for="installPlacement">Размещение</label><select class="inp" id="installPlacement"><option value="separate">Отдельный сервер</option><option value="same">Сервер панели</option></select></div><p id="installError" role="alert"></p></form>`,footer:'<button class="btn" data-close>Отмена</button><button class="btn primary" type="submit" form="cabinetNewForm">Добавить</button>',onMount(layer,close){layer.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await API.call('/api/cabinet-service/installations',{method:'POST',body:{name:layer.querySelector('#installName').value,public_url:layer.querySelector('#installURL').value,server_ip:layer.querySelector('#installIP').value,placement:layer.querySelector('#installPlacement').value}});close();await load();box.querySelector('[data-pane="install"]').click();}catch(err){layer.querySelector('#installError').textContent=err.message;}};}});
 box.querySelectorAll('[data-install]').forEach(b=>b.onclick=()=>{const i=data.installations.find(i=>i.id===b.dataset.install);if(!conf.enabled&&!i.last_seen_at){toast('Сначала опубликуйте кабинет и сохраните настройки');publish();return;}const issue=async()=>{try{const r=await API.call(`/api/cabinet-service/installations/${i.id}/token`,{method:'POST'});openModal({title:'Установка кабинета',icon:'download',size:'lg',body:`<p>Сначала направьте DNS домена <b>${esc(new URL(i.public_url).hostname)}</b> на <b>${esc(i.server_ip)}</b>. Откройте входящие TCP 80 и 443.</p><p>Войдите по SSH на этот сервер от root и выполните команду:</p><div class="copy-block"><pre class="txt mono">${esc(r.command)}</pre><button data-copy="${esc(r.command)}" aria-label="Скопировать команду">${I('copy',14)}</button></div><p class="hint">Ключ внутри команды показывается один раз. Установщик проверяет сервер и ключ, устанавливает службу и HTTPS. Данные базы остаются на панели. Если служба уже существует, настройки сохраняются, а повторная установка останавливается с инструкцией обновления.</p><p><a href="/cabinet-installation.html" target="_blank" rel="noopener">Установка, обновление и диагностика</a></p>`,footer:'<button class="btn primary" data-close>Готово</button>'});await load();box.querySelector('[data-pane="install"]').click();}catch(err){toast(err.message);}};if(i.token_prefix)confirmModal({title:'Обновить ключ сервера?',text:'Старый ключ перестанет работать. Установленный кабинет нужно будет перезапустить с новым ключом.',okText:'Обновить ключ',onOk:issue});else issue();});
 box.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=()=>confirmModal({title:'Отключить кабинет?',text:'Сайт и Mini App этого сервера перестанут получать данные. Аккаунты и подписки сохранятся.',okText:'Отключить',onOk:async()=>{await API.call(`/api/cabinet-service/installations/${b.dataset.revoke}/revoke`,{method:'POST'});await load();}}));
 if(!owner)box.querySelectorAll('form input,form textarea,form button').forEach(x=>x.disabled=true);
 }
 function row(k,r,a,al,b,bl){return `<div class="cabinet-row"><label>${al}<input class="inp" data-part="${a}" value="${esc(r[a]||'')}"></label><label>${bl}<textarea class="inp" data-part="${b}" rows="2">${esc(r[b]||'')}</textarea></label><button class="btn icon danger" type="button" data-remove-row aria-label="Удалить строку">${I('trash',14)}</button></div>`;}
 root.querySelector('#cabinetReload').onclick=load;await load();
 }
});
