'use strict';
const staffText=(ru,en)=>currentLang()==='en'?en:ru;
const staffRoles=()=>({owner:staffText('Владелец','Owner'),admin:staffText('Администратор','Administrator'),support:staffText('Поддержка','Support'),readonly:staffText('Наблюдатель','Read only')});
const roleOptions=(selected)=>Object.entries(staffRoles()).map(([v,t])=>`<option value="${v}" ${selected===v?'selected':''}>${t}</option>`).join('');
registerPage({id:'admin-profile',title:'Профиль администратора',group:'Аккаунт',icon:'user',nav:false,
  render(){return `<div class="page-head"><div><h1>${staffText('Мой профиль','My profile')}</h1><div class="desc">${staffText('Личные данные, пароль и защита входа.','Personal details, password and sign-in security.')}</div></div>${DB.admin?.role==='owner'?`<a class="btn" href="#/team">${I('users2',16)} ${staffText('Команда и доступ','Team and access')}</a>`:''}</div>
    <div class="grid g2" style="align-items:start"><div class="card"><div class="section-h"><div class="avatar">${esc(DB.admin.username.slice(0,2).toUpperCase())}</div><h2>${esc(DB.admin.username)}</h2><span class="bdg info">${staffRoles()[DB.admin.role]}</span></div>
    <form id="profileForm"><div class="field"><label for="profileUsername">${staffText('Логин','Username')}</label><input class="inp" id="profileUsername" autocomplete="username" required minlength="3" maxlength="64"></div>
    <div class="field"><label for="profileEmail">Email</label><input class="inp" id="profileEmail" type="email" autocomplete="email"><div class="hint">${staffText('Контактный адрес. Для входа используется логин.','Contact address. Use your username to sign in.')}</div></div>
    <div class="field"><label for="profilePassword">${staffText('Текущий пароль','Current password')}</label><input class="inp" id="profilePassword" type="password" autocomplete="current-password" required></div>
    <p class="sub-note" id="profileDates"></p><button class="btn primary" type="submit">${I('check',14)} ${staffText('Сохранить профиль','Save profile')}</button><p role="status" id="profileResult" class="sub-note"></p></form></div><div>${adminSecurityCard()}</div></div>`;},
  async bind(root){
    await bindAdminSecurity(root);
    const p=await API.call('/api/admin/profile');if(!root.isConnected)return;
    root.querySelector('#profileUsername').value=p.username;root.querySelector('#profileEmail').value=p.email||'';
    root.querySelector('#profileDates').textContent=staffText('Аккаунт создан: ','Account created: ')+fmtDT(p.created_at);
    root.querySelector('#profileForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;
      try {await API.call('/api/admin/profile',{method:'PATCH',body:{username:root.querySelector('#profileUsername').value,email:root.querySelector('#profileEmail').value||null,current_password:root.querySelector('#profilePassword').value}});
        DB.admin.username=root.querySelector('#profileUsername').value.trim();root.querySelector('#profilePassword').value='';root.querySelector('#profileResult').textContent=staffText('Профиль сохранён','Profile saved');toast(staffText('Профиль сохранён','Profile saved'));}
      catch(e){root.querySelector('#profileResult').textContent=e.message;toast(e.message,'err');}finally{b.disabled=false;}};
  }
});
registerPage({id:'team',title:'Команда и доступ',group:'Система',icon:'users2',nav:false,
  render(){return `<div class="page-head"><div><h1>${staffText('Команда и доступ','Team and access')}</h1><div class="desc">${staffText('Отдельный аккаунт для каждого сотрудника. Управление доступом — у владельца.','A separate account for each teammate. Owners manage access.')}</div></div><button class="btn primary" id="staffCreate">${I('plus',14)} ${staffText('Добавить сотрудника','Add teammate')}</button></div>
    <div class="grid g2" style="margin-bottom:20px"><div class="card"><h2>${I('chat',18)} ${staffText('Поддержка','Support')}</h2><p class="sub-note">${staffText('Клиенты, заметки, теги, устройства и ответы на обращения. Без управления платежами, тарифами, ключами и инфраструктурой.','Customers, notes, tags, devices and ticket replies. No payment, tariff, credential or infrastructure management.')}</p></div><div class="card"><h2>${I('shieldCheck',18)} ${staffText('Роли и отзыв доступа','Roles and revocation')}</h2><p class="sub-note">${staffText('Администратор управляет сервисом; наблюдатель просматривает данные. Только владелец управляет командой. Отключение сотрудника отзывает его сессии и API-токены.','Administrators manage the service; read-only staff view data. Only owners manage the team. Disabling a teammate revokes their sessions and API tokens.')}</p></div></div>
    <div class="tbl-wrap" id="staffList" aria-live="polite">${staffText('Загрузка…','Loading…')}</div>`;},
  async bind(root){const load=async()=>{const rows=await API.call('/api/team');if(!root.isConnected)return;
    root.querySelector('#staffList').innerHTML=`<table class="tbl"><thead><tr><th>${staffText('Сотрудник','Teammate')}</th><th>${staffText('Роль','Role')}</th><th>${staffText('Доступ','Access')}</th><th>2FA</th><th>${staffText('Последний вход','Last sign-in')}</th><th></th></tr></thead><tbody>${rows.map(a=>`<tr><td><b>${esc(a.username)}</b>${a.id===DB.admin.id?` <span class="chip">${staffText('Вы','You')}</span>`:''}<div class="sub-note">${esc(a.email||'')}</div></td><td>${staffRoles()[a.role]||esc(a.role)}</td><td><span class="bdg ${a.is_active?'ok':'neutral'}">${a.is_active?staffText('Активен','Active'):staffText('Отключён','Disabled')}</span></td><td>${a.totp_enabled?staffText('Включена','Enabled'):staffText('Выключена','Disabled')}</td><td>${a.last_login_at?fmtDT(a.last_login_at):staffText('Ещё не входил','Not signed in yet')}</td><td><button class="btn sm" data-staff="${a.id}">${staffText('Управление','Manage')}</button></td></tr>`).join('')}</tbody></table>`;
    root.querySelectorAll('[data-staff]').forEach(b=>b.onclick=()=>staffManage(rows.find(a=>String(a.id)===b.dataset.staff),load));};
    root.querySelector('#staffCreate').onclick=()=>staffCreate(load);await load();}
});
function staffCreate(load){openModal({title:staffText('Новый сотрудник','New teammate'),icon:'users2',size:'sm',body:`<form id="staffCreateForm"><div class="field"><label for="staffName">${staffText('Логин','Username')}</label><input class="inp" id="staffName" required minlength="3" maxlength="64" autocomplete="off"></div><div class="field"><label for="staffEmail">Email</label><input class="inp" id="staffEmail" type="email"></div><div class="field"><label for="staffRole">${staffText('Роль','Role')}</label><select class="inp" id="staffRole">${roleOptions('support')}</select></div><div class="field"><label for="staffPassword">${staffText('Пароль · 12–128 символов','Password · 12–128 characters')}</label><input class="inp" id="staffPassword" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></div><p class="sub-note">${staffText('Передайте сотруднику адрес панели, логин и пароль. После входа он сможет сменить пароль и включить 2FA в профиле.','Give the teammate the panel address, username and password. They can change the password and enable 2FA in their profile.')}</p></form>`,footer:`<button class="btn" data-close>${staffText('Отмена','Cancel')}</button><button class="btn primary" form="staffCreateForm" type="submit">${staffText('Создать аккаунт','Create account')}</button>`,onMount(layer,close){layer.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=layer.querySelector('[type=submit]');b.disabled=true;try{await API.call('/api/team',{method:'POST',body:{username:layer.querySelector('#staffName').value,email:layer.querySelector('#staffEmail').value||null,role:layer.querySelector('#staffRole').value,password:layer.querySelector('#staffPassword').value}});close();toast(staffText('Сотрудник добавлен','Teammate added'));await load();}catch(e){toast(e.message,'err');b.disabled=false;}};}});}
function staffManage(a,load){if(a.id===DB.admin.id){navigate('admin-profile');return;}openModal({title:esc(a.username),icon:'user',size:'sm',body:`<div class="field"><label>${staffText('Роль','Role')}</label><select class="inp" id="staffAccessRole">${roleOptions(a.role)}</select></div><div class="field"><label><input type="checkbox" id="staffActive" ${a.is_active?'checked':''}> ${staffText('Доступ к панели включён','Panel access enabled')}</label></div><p class="sub-note">${staffText('Изменение роли или доступа завершит сессии сотрудника и отзовёт его API-токены.','Changing the role or access revokes the teammate’s sessions and API tokens.')}</p><div class="actions"><button class="btn" id="staffReset">${staffText('Сбросить пароль','Reset password')}</button><button class="btn" id="staffRevoke">${staffText('Отозвать сессии','Revoke sessions')}</button></div>`,footer:`<button class="btn" data-close>${staffText('Закрыть','Close')}</button><button class="btn primary" id="staffSave">${staffText('Сохранить','Save')}</button>`,onMount(layer,close){
    layer.querySelector('#staffSave').onclick=async e=>{e.currentTarget.disabled=true;try{await API.call('/api/team/'+a.id,{method:'PATCH',body:{role:layer.querySelector('#staffAccessRole').value,is_active:layer.querySelector('#staffActive').checked}});close();toast(staffText('Доступ обновлён','Access updated'));await load();}catch(err){toast(err.message,'err');layer.querySelector('#staffSave').disabled=false;}};
    layer.querySelector('#staffRevoke').onclick=()=>confirmModal({title:staffText('Отозвать доступ с устройств?','Revoke device sessions?'),text:staffText('Сотруднику потребуется войти заново. Его API-токены также будут отозваны.','The teammate will need to sign in again. Their API tokens will also be revoked.'),okText:staffText('Отозвать','Revoke'),onOk:async()=>{await API.call('/api/team/'+a.id+'/sessions',{method:'DELETE'});toast(staffText('Сессии отозваны','Sessions revoked'));}});
    layer.querySelector('#staffReset').onclick=()=>openModal({title:staffText('Новый пароль сотрудника','New teammate password'),size:'sm',body:`<form id="staffResetForm"><label for="staffNewPassword">${staffText('Пароль · 12–128 символов','Password · 12–128 characters')}</label><input class="inp" type="password" id="staffNewPassword" required minlength="12" maxlength="128" autocomplete="new-password"><p class="sub-note">${staffText('Старый пароль перестанет работать, сессии и API-токены будут отозваны. Настройка 2FA сохранится.','The old password stops working; sessions and API tokens are revoked. 2FA stays enabled.')}</p></form>`,footer:`<button class="btn" data-close>${staffText('Отмена','Cancel')}</button><button class="btn primary" type="submit" form="staffResetForm">${staffText('Заменить пароль','Replace password')}</button>`,onMount(m,done){m.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=m.querySelector('[type=submit]');b.disabled=true;try{await API.call('/api/team/'+a.id+'/password',{method:'POST',body:{password:m.querySelector('#staffNewPassword').value}});done();toast(staffText('Пароль заменён','Password replaced'));}catch(e){toast(e.message,'err');b.disabled=false;}};}});
}});}

function adminSecurityCard(){return `        <div class="card" style="margin-top:var(--panel-gap,14px)">
          <div class="section-h" style="margin:0 0 12px"><h2>${I('shieldCheck',14)} Безопасность</h2></div>
          <div class="switch-row"><label class="switch"><input type="checkbox" id="sec2fa"><span class="tr"></span></label>
            <div class="sw-txt"><b>Двухфакторная аутентификация</b>
              <span id="sec2faNote">Код из приложения-аутентификатора при каждом входе</span></div></div>
          <div class="info-row"><span class="k">Passkeys</span>
            <span class="v" id="secPk">—</span>
            <button class="btn sm" style="margin-left:auto" id="pkBtn">${I('fingerprint',12)} Подробнее</button></div>
          <div class="info-row"><span class="k">Пароль</span><span class="v">вход по паролю</span>
            <button class="btn sm" style="margin-left:auto" id="secPwd">Сменить</button></div>
          <div class="info-row"><span class="k">Активные сессии</span><span class="v" id="secSess">—</span>
            <button class="btn sm" style="margin-left:auto" id="secKill">Завершить остальные</button></div>
        </div>
`;}
